pipeline:
  stages:
    - stage: "Build Orders Service"
      executionOrder: 0
      steps:
        - echo "Start build"
        - cmd: orders.bat --build-sln
          fromPath: scripts\
        - cmd: orders.bat --execute
          fromPath: scripts\
      timeLimitInMinutes: 5
