pipeline:
  stages:
    - stage: "Build Product Service"
      executionOrder: 0
      steps:
        - echo "Start build"
        - cmd: products.bat --build-sln
          fromPath: scripts\
        - cmd: products.bat --execute
          fromPath: scripts\
      timeLimitInMinutes: 5
